__version__ = '0.1.5'
VERSION = __version__
AUTHOR = 'jeffkit.info@gmail.com'

RATE_LIMIT_IP_PER_SECOND = 500
RATE_LIMIT_ACCOUNT_PER_HOUR = 2000

ORDER_SIDE_BID = 'BID'
ORDER_SIDE_ASK = 'ASK'

ORDER_STATE_PENDING = 'PENDING'
ORDER_STATE_FILLED = 'FILLED'
ORDER_STATE_CANCELED = 'CANCELED'

WITHDRAWALS_STATE_CONFIRMED = 'CONFIRMED'
WITHDRAWALS_STATE_UNCONFIRMED = 'UNCONFIRMED'

DEPOSIT_STATE_CONFIRMED = 'CONFIRMED'
DEPOSIT_STATE_UNCONFIRMED = 'UNCONFIRMED'
